# Generated by Django 3.1.3 on 2020-12-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20201219_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msg',
            options={'managed': False},
        ),
    ]
