# Generated by Django 3.1.1 on 2021-01-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('usr_msg', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('no', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'msg',
                'managed': (True,),
            },
        ),
    ]
